-- // --- BÖLÜM 1 / 1 BAŞI - (install.sql - Hata Düzeltilmiş ve Sıralanmış Tam Sürüm)

-- WHMCS BTK Raporları Modülü Veritabanı Kurulum Script'i
-- Bu script, modül aktive edildiğinde çalıştırılacaktır.
-- Tüm tablolar 'IF NOT EXISTS' ile oluşturulmuştur, böylece tekrar çalıştırmada hata vermez.

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

-- 1. mod_btk_ayarlar (Bağımsız)
CREATE TABLE IF NOT EXISTS `mod_btk_ayarlar` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `ayar_adi` VARCHAR(191) NOT NULL,
    `ayar_degeri` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `ayar_adi_unique` (`ayar_adi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. mod_btk_yetki_turleri (Bağımsız - Daha sonra mod_btk_yetki_turleri_referans ve secili olarak ayrılacak)
CREATE TABLE IF NOT EXISTS `mod_btk_yetki_turleri` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `yetki_kodu` VARCHAR(50) NOT NULL COMMENT 'BTK tarafından tanımlanan kod',
    `yetki_aciklama` VARCHAR(255) NOT NULL COMMENT 'BTK tarafından tanımlanan açıklama',
    `secili_mi` TINYINT(1) DEFAULT 0 COMMENT '0: Seçili Değil, 1: Seçili (İşletmeci bu yetkiye sahip)',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `yetki_kodu_unique` (`yetki_kodu`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Adres Tabloları (Birbirlerine bağımlı)
CREATE TABLE IF NOT EXISTS `mod_btk_adres_il` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `il_adi` VARCHAR(100) NOT NULL,
    `plaka_kodu` VARCHAR(2) DEFAULT NULL,
    `uavt_kodu` VARCHAR(20) DEFAULT NULL,
    UNIQUE KEY `il_adi_unique` (`il_adi`),
    UNIQUE KEY `plaka_kodu_unique` (`plaka_kodu`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_adres_ilce` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `il_id` INT NOT NULL,
    `ilce_adi` VARCHAR(100) NOT NULL,
    `uavt_kodu` VARCHAR(20) DEFAULT NULL,
    FOREIGN KEY (`il_id`) REFERENCES `mod_btk_adres_il`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY `uniq_il_ilce` (`il_id`, `ilce_adi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_adres_mahalle` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `ilce_id` INT NOT NULL,
    `mahalle_adi` VARCHAR(191) NOT NULL,
    `uavt_kodu` VARCHAR(20) DEFAULT NULL,
    `posta_kodu` VARCHAR(10) DEFAULT NULL,
    FOREIGN KEY (`ilce_id`) REFERENCES `mod_btk_adres_ilce`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX `idx_mahalle_ilce_adi` (`ilce_id`, `mahalle_adi`) -- Unique değil, birden fazla mahalle olabilir aynı isimde farklı ilçelerde.
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Personel Departmanları (Bağımsız)
CREATE TABLE IF NOT EXISTS `mod_btk_personel_departmanlari` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `departman_adi` VARCHAR(191) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `departman_adi_unique` (`departman_adi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. Personel Tablosu (Departman ve Adreslere bağımlı)
CREATE TABLE IF NOT EXISTS `mod_btk_personel` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `admin_id` INT DEFAULT NULL COMMENT 'tbladmins.id ile ilişkili, NULL olabilir',
    `firma_unvani` VARCHAR(255) DEFAULT NULL,
    `ad` VARCHAR(100) DEFAULT NULL,
    `soyad` VARCHAR(100) DEFAULT NULL,
    `tc_kimlik_no` VARCHAR(11) DEFAULT NULL,
    `uyruk_iso_kodu` CHAR(3) DEFAULT 'TUR',
    `unvan_gorev` VARCHAR(255) DEFAULT NULL,
    `departman_id` INT DEFAULT NULL,
    `mobil_telefonu` VARCHAR(20) DEFAULT NULL,
    `sabit_telefonu` VARCHAR(20) DEFAULT NULL,
    `eposta_adresi` VARCHAR(191) DEFAULT NULL,
    `ev_adresi` TEXT DEFAULT NULL,
    `acil_durum_kisi_adi` VARCHAR(255) DEFAULT NULL,
    `acil_durum_kisi_telefonu` VARCHAR(20) DEFAULT NULL,
    `ise_baslama_tarihi` DATE DEFAULT NULL,
    `isten_ayrilma_tarihi` DATE DEFAULT NULL,
    `is_birakma_nedeni` TEXT DEFAULT NULL,
    `btk_listesine_eklensin` TINYINT(1) DEFAULT 1,
    `gorev_bolgesi_il_id` INT DEFAULT NULL,
    `gorev_bolgesi_ilce_id` INT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `admin_id_unique_if_not_null` (`admin_id`), -- Sadece doluysa unique olmalı, bu MySQL'de direkt desteklenmez, uygulama katmanında kontrol edilmeli veya trigger ile. Şimdilik admin_id UNIQUE.
    INDEX `idx_personel_tckn` (`tc_kimlik_no`),
    FOREIGN KEY (`departman_id`) REFERENCES `mod_btk_personel_departmanlari`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`gorev_bolgesi_il_id`) REFERENCES `mod_btk_adres_il`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`gorev_bolgesi_ilce_id`) REFERENCES `mod_btk_adres_ilce`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. ISS POP Noktaları (Adreslere bağımlı)
CREATE TABLE IF NOT EXISTS `mod_btk_iss_pop_noktalari` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `pop_adi` VARCHAR(255) NOT NULL,
    `il_id` INT DEFAULT NULL,
    `ilce_id` INT DEFAULT NULL,
    `mahalle_id` INT DEFAULT NULL,
    `adres_detay` TEXT DEFAULT NULL,
    `koordinatlar` VARCHAR(100) DEFAULT NULL,
    `yayin_yapilan_ssid` VARCHAR(191) DEFAULT NULL,
    `sunucu_bilgisi` VARCHAR(255) DEFAULT NULL,
    `aktif_mi` TINYINT(1) DEFAULT 1,
    `cihaz_turu` VARCHAR(100) DEFAULT NULL,     -- Excel'den gelen alanlar eklendi
    `cihaz_markasi` VARCHAR(100) DEFAULT NULL,
    `cihaz_modeli` VARCHAR(100) DEFAULT NULL,
    `ip_adresi` VARCHAR(255) DEFAULT NULL,      -- Excel'den gelen alanlar eklendi
    `pop_tipi` VARCHAR(100) DEFAULT NULL,       -- Excel'den gelen alanlar eklendi (TÜRÜ)
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`il_id`) REFERENCES `mod_btk_adres_il`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`ilce_id`) REFERENCES `mod_btk_adres_ilce`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`mahalle_id`) REFERENCES `mod_btk_adres_mahalle`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY `pop_adi_ilce_ssid_unique` (`pop_adi`(191), `ilce_id`, `yayin_yapilan_ssid`(191)) -- Daha anlamlı unique key
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. Abone Rehber (Adres, POP'a bağımlı olabilir)
CREATE TABLE IF NOT EXISTS `mod_btk_abone_rehber` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `whmcs_user_id` INT DEFAULT NULL,
    `whmcs_service_id` INT DEFAULT NULL,
    `OPERATOR_KOD` VARCHAR(10) DEFAULT NULL,
    `MUSTERI_ID` VARCHAR(50) DEFAULT NULL,
    `HAT_NO` VARCHAR(50) DEFAULT NULL,
    `HAT_DURUM` CHAR(1) DEFAULT NULL,
    `HAT_DURUM_KODU` VARCHAR(10) DEFAULT NULL,
    `HAT_DURUM_KODU_ACIKLAMA` VARCHAR(255) DEFAULT NULL,
    `MUSTERI_HAREKET_KODU` VARCHAR(10) DEFAULT NULL,
    `MUSTERI_HAREKET_ACIKLAMA` VARCHAR(255) DEFAULT NULL,
    `MUSTERI_HAREKET_ZAMANI` VARCHAR(14) DEFAULT NULL,
    `HIZMET_TIPI` VARCHAR(50) DEFAULT NULL,
    `MUSTERI_TIPI` VARCHAR(50) DEFAULT NULL,
    `ABONE_BASLANGIC` VARCHAR(14) DEFAULT NULL,
    `ABONE_BITIS` VARCHAR(14) DEFAULT NULL,
    `ABONE_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_SOYADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_TC_KIMLIK_NO` VARCHAR(11) DEFAULT NULL,
    `ABONE_PASAPORT_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_UNVAN` VARCHAR(255) DEFAULT NULL,
    `ABONE_VERGI_NUMARASI` VARCHAR(20) DEFAULT NULL,
    `ABONE_MERSIS_NUMARASI` VARCHAR(20) DEFAULT NULL,
    `ABONE_CINSIYET` CHAR(1) DEFAULT NULL,
    `ABONE_UYRUK` CHAR(3) DEFAULT NULL,
    `ABONE_BABA_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_ANA_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_ANNE_KIZLIK_SOYADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_DOGUM_YERI` VARCHAR(100) DEFAULT NULL,
    `ABONE_DOGUM_TARIHI` VARCHAR(8) DEFAULT NULL,
    `ABONE_MESLEK` VARCHAR(10) DEFAULT NULL,
    `ABONE_TARIFE` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_CILT_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_KUTUK_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_SAYFA_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_MAHALLE_KOY` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_TIPI` CHAR(1) DEFAULT NULL,
    `ABONE_KIMLIK_SERI_NO` VARCHAR(20) DEFAULT NULL,
    `ABONE_KIMLIK_VERILDIGI_YER` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_VERILDIGI_TARIH` VARCHAR(8) DEFAULT NULL,
    `ABONE_KIMLIK_AIDIYETI` CHAR(1) DEFAULT NULL,
    `ABONE_ADRES_TESIS_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_TESIS_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_TESIS_MAHALLE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_TESIS_CADDE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_TESIS_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_TESIS_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_TESIS_POSTA_KODU` VARCHAR(10) DEFAULT NULL,
    `ABONE_ADRES_TESIS_ADRES_KODU` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_IRTIBAT_TEL_NO_1` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_IRTIBAT_TEL_NO_2` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_E_MAIL` VARCHAR(191) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_MAHALLE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_CADDE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_POSTA_KODU` VARCHAR(10) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_ADRES_KODU` VARCHAR(20) DEFAULT NULL,
    `KURUM_YETKILI_ADI` VARCHAR(100) DEFAULT NULL,
    `KURUM_YETKILI_SOYADI` VARCHAR(100) DEFAULT NULL,
    `KURUM_YETKILI_TCKIMLIK_NO` VARCHAR(11) DEFAULT NULL,
    `KURUM_YETKILI_TELEFON` VARCHAR(20) DEFAULT NULL,
    `KURUM_ADRES` TEXT DEFAULT NULL,
    `AKTIVASYON_BAYI_ADI` VARCHAR(255) DEFAULT NULL,
    `AKTIVASYON_BAYI_ADRESI` TEXT DEFAULT NULL,
    `AKTIVASYON_KULLANICI` VARCHAR(100) DEFAULT NULL,
    `GUNCELLEYEN_BAYI_ADI` VARCHAR(255) DEFAULT NULL,
    `GUNCELLEYEN_BAYI_ADRESI` TEXT DEFAULT NULL,
    `GUNCELLEYEN_KULLANICI` VARCHAR(100) DEFAULT NULL,
    `STATIK_IP` VARCHAR(255) DEFAULT NULL,
    `ISS_HIZ_PROFILI` VARCHAR(100) DEFAULT NULL,
    `ISS_KULLANICI_ADI` VARCHAR(100) DEFAULT NULL,
    `ISS_POP_BILGISI` VARCHAR(255) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_rehber_whmcs_user_id` (`whmcs_user_id`),
    UNIQUE INDEX `uidx_rehber_whmcs_service_id` (`whmcs_service_id`),
    INDEX `idx_rehber_abone_tc_kimlik_no` (`ABONE_TC_KIMLIK_NO`),
    INDEX `idx_rehber_abone_vergi_numarasi` (`ABONE_VERGI_NUMARASI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 8. Abone Hareket Canlı (Abone Rehbere bağımlı)
CREATE TABLE IF NOT EXISTS `mod_btk_abone_hareket_canli` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `abone_rehber_id` BIGINT DEFAULT NULL,
    `whmcs_user_id` INT DEFAULT NULL,
    `whmcs_service_id` INT DEFAULT NULL,
    -- ... (mod_btk_abone_rehber'deki tüm alanlar buraya da kopyalanacak, sütun adları AYNI olmalı) ...
    `OPERATOR_KOD` VARCHAR(10) DEFAULT NULL, `MUSTERI_ID` VARCHAR(50) DEFAULT NULL, `HAT_NO` VARCHAR(50) DEFAULT NULL, `HAT_DURUM` CHAR(1) DEFAULT NULL, `HAT_DURUM_KODU` VARCHAR(10) DEFAULT NULL, `HAT_DURUM_KODU_ACIKLAMA` VARCHAR(255) DEFAULT NULL, `MUSTERI_HAREKET_KODU` VARCHAR(10) DEFAULT NULL, `MUSTERI_HAREKET_ACIKLAMA` VARCHAR(255) DEFAULT NULL, `MUSTERI_HAREKET_ZAMANI` VARCHAR(14) DEFAULT NULL, `HIZMET_TIPI` VARCHAR(50) DEFAULT NULL, `MUSTERI_TIPI` VARCHAR(50) DEFAULT NULL, `ABONE_BASLANGIC` VARCHAR(14) DEFAULT NULL, `ABONE_BITIS` VARCHAR(14) DEFAULT NULL, `ABONE_ADI` VARCHAR(100) DEFAULT NULL, `ABONE_SOYADI` VARCHAR(100) DEFAULT NULL, `ABONE_TC_KIMLIK_NO` VARCHAR(11) DEFAULT NULL, `ABONE_PASAPORT_NO` VARCHAR(50) DEFAULT NULL, `ABONE_UNVAN` VARCHAR(255) DEFAULT NULL, `ABONE_VERGI_NUMARASI` VARCHAR(20) DEFAULT NULL, `ABONE_MERSIS_NUMARASI` VARCHAR(20) DEFAULT NULL, `ABONE_CINSIYET` CHAR(1) DEFAULT NULL, `ABONE_UYRUK` CHAR(3) DEFAULT NULL, `ABONE_BABA_ADI` VARCHAR(100) DEFAULT NULL, `ABONE_ANA_ADI` VARCHAR(100) DEFAULT NULL, `ABONE_ANNE_KIZLIK_SOYADI` VARCHAR(100) DEFAULT NULL, `ABONE_DOGUM_YERI` VARCHAR(100) DEFAULT NULL, `ABONE_DOGUM_TARIHI` VARCHAR(8) DEFAULT NULL, `ABONE_MESLEK` VARCHAR(10) DEFAULT NULL, `ABONE_TARIFE` VARCHAR(100) DEFAULT NULL, `ABONE_KIMLIK_CILT_NO` VARCHAR(10) DEFAULT NULL, `ABONE_KIMLIK_KUTUK_NO` VARCHAR(10) DEFAULT NULL, `ABONE_KIMLIK_SAYFA_NO` VARCHAR(10) DEFAULT NULL, `ABONE_KIMLIK_IL` VARCHAR(100) DEFAULT NULL, `ABONE_KIMLIK_ILCE` VARCHAR(100) DEFAULT NULL, `ABONE_KIMLIK_MAHALLE_KOY` VARCHAR(100) DEFAULT NULL, `ABONE_KIMLIK_TIPI` CHAR(1) DEFAULT NULL, `ABONE_KIMLIK_SERI_NO` VARCHAR(20) DEFAULT NULL, `ABONE_KIMLIK_VERILDIGI_YER` VARCHAR(100) DEFAULT NULL, `ABONE_KIMLIK_VERILDIGI_TARIH` VARCHAR(8) DEFAULT NULL, `ABONE_KIMLIK_AIDIYETI` CHAR(1) DEFAULT NULL, `ABONE_ADRES_TESIS_IL` VARCHAR(100) DEFAULT NULL, `ABONE_ADRES_TESIS_ILCE` VARCHAR(100) DEFAULT NULL, `ABONE_ADRES_TESIS_MAHALLE` VARCHAR(255) DEFAULT NULL, `ABONE_ADRES_TESIS_CADDE` VARCHAR(255) DEFAULT NULL, `ABONE_ADRES_TESIS_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL, `ABONE_ADRES_TESIS_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL, `ABONE_ADRES_TESIS_POSTA_KODU` VARCHAR(10) DEFAULT NULL, `ABONE_ADRES_TESIS_ADRES_KODU` VARCHAR(20) DEFAULT NULL, `ABONE_ADRES_IRTIBAT_TEL_NO_1` VARCHAR(20) DEFAULT NULL, `ABONE_ADRES_IRTIBAT_TEL_NO_2` VARCHAR(20) DEFAULT NULL, `ABONE_ADRES_E_MAIL` VARCHAR(191) DEFAULT NULL, `ABONE_ADRES_YERLESIM_IL` VARCHAR(100) DEFAULT NULL, `ABONE_ADRES_YERLESIM_ILCE` VARCHAR(100) DEFAULT NULL, `ABONE_ADRES_YERLESIM_MAHALLE` VARCHAR(255) DEFAULT NULL, `ABONE_ADRES_YERLESIM_CADDE` VARCHAR(255) DEFAULT NULL, `ABONE_ADRES_YERLESIM_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL, `ABONE_ADRES_YERLESIM_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL, `ABONE_ADRES_YERLESIM_POSTA_KODU` VARCHAR(10) DEFAULT NULL, `ABONE_ADRES_YERLESIM_ADRES_KODU` VARCHAR(20) DEFAULT NULL, `KURUM_YETKILI_ADI` VARCHAR(100) DEFAULT NULL, `KURUM_YETKILI_SOYADI` VARCHAR(100) DEFAULT NULL, `KURUM_YETKILI_TCKIMLIK_NO` VARCHAR(11) DEFAULT NULL, `KURUM_YETKILI_TELEFON` VARCHAR(20) DEFAULT NULL, `KURUM_ADRES` TEXT DEFAULT NULL, `AKTIVASYON_BAYI_ADI` VARCHAR(255) DEFAULT NULL, `AKTIVASYON_BAYI_ADRESI` TEXT DEFAULT NULL, `AKTIVASYON_KULLANICI` VARCHAR(100) DEFAULT NULL, `GUNCELLEYEN_BAYI_ADI` VARCHAR(255) DEFAULT NULL, `GUNCELLEYEN_BAYI_ADRESI` TEXT DEFAULT NULL, `GUNCELLEYEN_KULLANICI` VARCHAR(100) DEFAULT NULL, `STATIK_IP` VARCHAR(255) DEFAULT NULL, `ISS_HIZ_PROFILI` VARCHAR(100) DEFAULT NULL, `ISS_KULLANICI_ADI` VARCHAR(100) DEFAULT NULL, `ISS_POP_BILGISI` VARCHAR(255) DEFAULT NULL,
    `gonderildi_ana_ftp` TINYINT(1) DEFAULT 0,
    `gonderildi_yedek_ftp` TINYINT(1) DEFAULT 0,
    `gonderildigi_dosya_adi_ana` VARCHAR(255) DEFAULT NULL,
    `gonderildigi_dosya_adi_yedek` VARCHAR(255) DEFAULT NULL,
    `gonderme_zamani_ana` TIMESTAMP NULL DEFAULT NULL,
    `gonderme_zamani_yedek` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`abone_rehber_id`) REFERENCES `mod_btk_abone_rehber`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX `idx_hareket_whmcs_service_id` (`whmcs_service_id`),
    INDEX `idx_hareket_gonderildi_ana` (`gonderildi_ana_ftp`),
    INDEX `idx_hareket_gonderildi_yedek` (`gonderildi_yedek_ftp`),
    INDEX `idx_hareket_musteri_hareket_zamani` (`MUSTERI_HAREKET_ZAMANI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Arşivlenmiş abone hareketlerini tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_abone_hareket_arsiv` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `abone_rehber_id` BIGINT DEFAULT NULL,
    `whmcs_user_id` INT DEFAULT NULL,
    `whmcs_service_id` INT DEFAULT NULL,
    `OPERATOR_KOD` VARCHAR(10) DEFAULT NULL,
    `MUSTERI_ID` VARCHAR(50) DEFAULT NULL,
    `HAT_NO` VARCHAR(50) DEFAULT NULL,
    `HAT_DURUM` CHAR(1) DEFAULT NULL,
    `HAT_DURUM_KODU` VARCHAR(10) DEFAULT NULL,
    `HAT_DURUM_KODU_ACIKLAMA` VARCHAR(255) DEFAULT NULL,
    `MUSTERI_HAREKET_KODU` VARCHAR(10) DEFAULT NULL,
    `MUSTERI_HAREKET_ACIKLAMA` VARCHAR(255) DEFAULT NULL,
    `MUSTERI_HAREKET_ZAMANI` VARCHAR(14) DEFAULT NULL,
    `HIZMET_TIPI` VARCHAR(50) DEFAULT NULL,
    `MUSTERI_TIPI` VARCHAR(50) DEFAULT NULL,
    `ABONE_BASLANGIC` VARCHAR(14) DEFAULT NULL,
    `ABONE_BITIS` VARCHAR(14) DEFAULT NULL,
    `ABONE_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_SOYADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_TC_KIMLIK_NO` VARCHAR(11) DEFAULT NULL,
    `ABONE_PASAPORT_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_UNVAN` VARCHAR(255) DEFAULT NULL,
    `ABONE_VERGI_NUMARASI` VARCHAR(20) DEFAULT NULL,
    `ABONE_MERSIS_NUMARASI` VARCHAR(20) DEFAULT NULL,
    `ABONE_CINSIYET` CHAR(1) DEFAULT NULL,
    `ABONE_UYRUK` CHAR(3) DEFAULT NULL,
    `ABONE_BABA_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_ANA_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_ANNE_KIZLIK_SOYADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_DOGUM_YERI` VARCHAR(100) DEFAULT NULL,
    `ABONE_DOGUM_TARIHI` VARCHAR(8) DEFAULT NULL,
    `ABONE_MESLEK` VARCHAR(10) DEFAULT NULL,
    `ABONE_TARIFE` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_CILT_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_KUTUK_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_SAYFA_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_MAHALLE_KOY` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_TIPI` CHAR(1) DEFAULT NULL,
    `ABONE_KIMLIK_SERI_NO` VARCHAR(20) DEFAULT NULL,
    `ABONE_KIMLIK_VERILDIGI_YER` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_VERILDIGI_TARIH` VARCHAR(8) DEFAULT NULL,
    `ABONE_KIMLIK_AIDIYETI` CHAR(1) DEFAULT NULL,
    `ABONE_ADRES_TESIS_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_TESIS_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_TESIS_MAHALLE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_TESIS_CADDE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_TESIS_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_TESIS_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_TESIS_POSTA_KODU` VARCHAR(10) DEFAULT NULL,
    `ABONE_ADRES_TESIS_ADRES_KODU` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_IRTIBAT_TEL_NO_1` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_IRTIBAT_TEL_NO_2` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_E_MAIL` VARCHAR(191) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_MAHALLE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_CADDE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_POSTA_KODU` VARCHAR(10) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_ADRES_KODU` VARCHAR(20) DEFAULT NULL,
    `KURUM_YETKILI_ADI` VARCHAR(100) DEFAULT NULL,
    `KURUM_YETKILI_SOYADI` VARCHAR(100) DEFAULT NULL,
    `KURUM_YETKILI_TCKIMLIK_NO` VARCHAR(11) DEFAULT NULL,
    `KURUM_YETKILI_TELEFON` VARCHAR(20) DEFAULT NULL,
    `KURUM_ADRES` TEXT DEFAULT NULL,
    `AKTIVASYON_BAYI_ADI` VARCHAR(255) DEFAULT NULL,
    `AKTIVASYON_BAYI_ADRESI` TEXT DEFAULT NULL,
    `AKTIVASYON_KULLANICI` VARCHAR(100) DEFAULT NULL,
    `GUNCELLEYEN_BAYI_ADI` VARCHAR(255) DEFAULT NULL,
    `GUNCELLEYEN_BAYI_ADRESI` TEXT DEFAULT NULL,
    `GUNCELLEYEN_KULLANICI` VARCHAR(100) DEFAULT NULL,
    `STATIK_IP` VARCHAR(255) DEFAULT NULL,
    `ISS_HIZ_PROFILI` VARCHAR(100) DEFAULT NULL,
    `ISS_KULLANICI_ADI` VARCHAR(100) DEFAULT NULL,
    `ISS_POP_BILGISI` VARCHAR(255) DEFAULT NULL,
    `gonderildi_ana_ftp` TINYINT(1) DEFAULT 1,
    `gonderildi_yedek_ftp` TINYINT(1) DEFAULT 1,
    `gonderildigi_dosya_adi_ana` VARCHAR(255) DEFAULT NULL,
    `gonderildigi_dosya_adi_yedek` VARCHAR(255) DEFAULT NULL,
    `gonderme_zamani_ana` TIMESTAMP NULL DEFAULT NULL,
    `gonderme_zamani_yedek` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP NULL DEFAULT NULL, -- Canlı tablodaki created_at değeri buraya kopyalanacak
    `arsivlenme_tarihi` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_arsiv_whmcs_service_id` (`whmcs_service_id`),
    INDEX `idx_arsiv_musteri_hareket_zamani` (`MUSTERI_HAREKET_ZAMANI`),
    INDEX `idx_arsiv_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- 10. Diğer Referans Tabloları (Bağımsız)
CREATE TABLE IF NOT EXISTS `mod_btk_ref_hat_durum_kodlari` ( `kod` VARCHAR(10) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'BTK EK-1';
CREATE TABLE IF NOT EXISTS `mod_btk_ref_musteri_hareket_kodlari` ( `kod` VARCHAR(10) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'BTK EK-2';
CREATE TABLE IF NOT EXISTS `mod_btk_ref_hizmet_tipleri` ( `kod` VARCHAR(50) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL, `ana_yetki_grup` VARCHAR(50) DEFAULT NULL COMMENT 'Bu hizmet tipinin ait olduğu ana BTK Yetki Grubu (ISS, STH vb.)' ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'BTK EK-3';
CREATE TABLE IF NOT EXISTS `mod_btk_ref_musteri_tipleri` ( `kod` VARCHAR(20) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'BTK EK-4 (Müşteri Tipleri)';
CREATE TABLE IF NOT EXISTS `mod_btk_ref_kimlik_tipleri` ( `kod` VARCHAR(10) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL, `ulke_kodu_gerekli` TINYINT(1) DEFAULT 0 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'BTK EK-5 (Kimlik Tipleri)';
CREATE TABLE IF NOT EXISTS `mod_btk_ref_kimlik_aidiyeti` ( `kod` CHAR(1) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'BTK EK-5 (Kimlik Aidiyeti)';
CREATE TABLE IF NOT EXISTS `mod_btk_ref_cinsiyet` ( `kod` CHAR(1) PRIMARY KEY, `aciklama` VARCHAR(50) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_hat_durum` ( `kod` CHAR(1) PRIMARY KEY, `aciklama` VARCHAR(50) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_meslek_kodlari` ( `kod` VARCHAR(10) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT 'BTK EK-6 (Meslekler)';
CREATE TABLE IF NOT EXISTS `mod_btk_ref_ulkeler` ( `iso_kodu` CHAR(3) PRIMARY KEY, `ulke_adi_tr` VARCHAR(100) NOT NULL, `ulke_adi_en` VARCHAR(100) DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 11. mod_btk_gonderilen_dosyalar (Bağımsız)
CREATE TABLE IF NOT EXISTS `mod_btk_gonderilen_dosyalar` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `dosya_adi` VARCHAR(255) NOT NULL,
    `dosya_tipi` ENUM('REHBER', 'HAREKET', 'PERSONEL') NOT NULL,
    `ftp_sunucu_tipi` ENUM('ANA', 'YEDEK') NOT NULL DEFAULT 'ANA',
    `gonderme_zamani` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `cnt_numarasi` VARCHAR(2) NOT NULL DEFAULT '01',
    `dosya_icerik_hash` VARCHAR(64) DEFAULT NULL,
    `kayit_sayisi` INT DEFAULT 0,
    `ftp_gonderim_durumu` ENUM('BASARILI', 'BASARISIZ', 'BEKLIYOR', 'ATLANDI') DEFAULT 'BEKLIYOR',
    `ftp_hata_mesaji` TEXT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `uidx_dosya_adi_sunucu_tipi` (`dosya_adi`(191), `ftp_sunucu_tipi`) -- Index prefix for long varchars
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 12. mod_btk_logs (Bağımsız)
CREATE TABLE IF NOT EXISTS `mod_btk_logs` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `log_tarihi` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `log_seviyesi` ENUM('INFO', 'WARNING', 'ERROR', 'DEBUG', 'CRITICAL', 'BAŞARILI', 'UYARI', 'HATA', 'BİLGİ') DEFAULT 'INFO',
    `islem` VARCHAR(255) DEFAULT NULL,
    `mesaj` TEXT DEFAULT NULL,
    `detay` TEXT DEFAULT NULL,
    `whmcs_admin_id` INT DEFAULT NULL,
    `whmcs_user_id` INT DEFAULT NULL,
    `whmcs_service_id` INT DEFAULT NULL,
    `ip_adresi` VARCHAR(45) DEFAULT NULL,
    INDEX `idx_logs_tarih_seviye` (`log_tarihi`, `log_seviyesi`),
    INDEX `idx_logs_islem` (`islem`(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 13. mod_btk_product_group_mappings (mod_btk_yetki_turleri ve mod_btk_ref_hizmet_tipleri'ne bağımlı)
CREATE TABLE IF NOT EXISTS `mod_btk_product_group_mappings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `whmcs_product_group_id` INT NOT NULL,
    `btk_yetki_turu_id` INT NOT NULL,
    `btk_hizmet_tipi_kodu` VARCHAR(50) NOT NULL COMMENT 'mod_btk_ref_hizmet_tipleri.kod ile FK',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`btk_yetki_turu_id`) REFERENCES `mod_btk_yetki_turleri`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`btk_hizmet_tipi_kodu`) REFERENCES `mod_btk_ref_hizmet_tipleri`(`kod`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY `whmcs_product_group_id_unique` (`whmcs_product_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 14. mod_btk_hizmet_operasyonel_detaylar (Bağımsız - tblhosting.id ile ilişkili ama FK yok)
CREATE TABLE IF NOT EXISTS `mod_btk_hizmet_operasyonel_detaylar` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `hizmet_id` INT NOT NULL,
    `aile_filtresi_aktif` TINYINT(1) DEFAULT 0,
    `mac_adresleri` TEXT DEFAULT NULL,
    `cihaz_seri_no` TEXT DEFAULT NULL,
    `wifi_sifresi` VARCHAR(255) DEFAULT NULL,
    `kurulum_notlari` TEXT DEFAULT NULL,
    `cihaz_turu` ENUM('INDOOR', 'OUTDOOR', 'DIGER') DEFAULT NULL,
    `cihaz_modeli` VARCHAR(255) DEFAULT NULL,
    `kurulum_sinyal_kalitesi` VARCHAR(100) DEFAULT NULL,
    `tesis_koordinatlari` VARCHAR(100) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `hizmet_id_unique` (`hizmet_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
-- // --- BÖLÜM 1 / 1 SONU - (install.sql - Hata Düzeltilmiş ve Sıralanmış Tam Sürüm)