-- WHMCS BTK Raporlama Modülü - Veritabanı Kurulum Script'i
-- Sürüm: 20.0.0 (Operasyon PHOENIX)

CREATE TABLE IF NOT EXISTS `mod_btk_settings` (
    `setting` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `value` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    PRIMARY KEY (`setting`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_yetki_turleri_referans` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `yetki_kodu` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE,
    `yetki_adi` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `grup` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_secili_yetki_turleri` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `yetki_kodu` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE,
    `aktif` BOOLEAN NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_ek3_hizmet_tipleri` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `hizmet_tipi_kodu` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE,
    `hizmet_tipi_aciklamasi` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `ana_yetki_grup` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_product_group_mappings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `gid` INT NOT NULL UNIQUE,
    `ana_btk_yetki_kodu` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `ek3_hizmet_tipi_kodu` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_adres_il` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `il_adi` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE, `plaka_kodu` VARCHAR(2) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_adres_ilce` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `il_id` INT NOT NULL, `ilce_adi` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, UNIQUE KEY `il_ilce_unique` (`il_id`, `ilce_adi`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_adres_mahalle` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `ilce_id` INT NOT NULL, `mahalle_adi` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL, `posta_kodu` VARCHAR(10) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_personel_departmanlari` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `departman_adi` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL UNIQUE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_personel` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `whmcs_admin_id` INT UNIQUE, `firma_unvani` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `ad` VARCHAR(100), `soyad` VARCHAR(100), `tckn` VARCHAR(11), `dogum_tarihi` DATE, `unvan` VARCHAR(100), `departman_id` INT, `mobil_tel` VARCHAR(20), `sabit_tel` VARCHAR(20), `eposta` VARCHAR(255), `acik_adres` TEXT, `acil_durum_kisi_adi` VARCHAR(200), `acil_durum_kisi_gsm` VARCHAR(20), `ise_baslama_tarihi` DATE, `isten_ayrilma_tarihi` DATE, `is_birakma_nedeni` TEXT, `btk_listesinde_goster` BOOLEAN NOT NULL DEFAULT 1, `aktif` BOOLEAN NOT NULL DEFAULT 1, `cinsiyet` ENUM('E', 'K'), `ogrenim_durumu` VARCHAR(100), `personel_statusu` VARCHAR(100), `engelli_mi` BOOLEAN NOT NULL DEFAULT 0, `yabanci_uyruklu_mu` BOOLEAN NOT NULL DEFAULT 0, INDEX `idx_personel_tckn` (`tckn`), INDEX `idx_personel_eposta` (`eposta`(191)) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_iss_pop_noktalari` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `pop_adi` VARCHAR(255), `yayin_yapilan_ssid` VARCHAR(255), `ip_adresi` VARCHAR(255), `pop_tipi` VARCHAR(100), `cihaz_markasi` VARCHAR(100), `cihaz_modeli` VARCHAR(100), `il_id` INT, `ilce_id` INT, `mahalle_id` INT, `tam_adres` TEXT, `pop_koordinat_enlem` VARCHAR(20), `pop_koordinat_boylam` VARCHAR(20), `aktif_pasif_durum` BOOLEAN NOT NULL DEFAULT 1, `izleme_aktif` BOOLEAN NOT NULL DEFAULT 0, `izleme_ip_adresi` VARCHAR(45), `izleme_portlari` VARCHAR(255), `izleme_tipi` ENUM('PING', 'PORT') DEFAULT 'PING', `son_izleme_zamani` TIMESTAMP NULL, `canli_durum` ENUM('UNKNOWN', 'ONLINE', 'OFFLINE', 'HIGH_LATENCY') NOT NULL DEFAULT 'UNKNOWN', `son_yanit_suresi` INT ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_abone_rehber` ( `id` BIGINT AUTO_INCREMENT PRIMARY KEY, `whmcs_client_id` INT, `whmcs_service_id` INT UNIQUE, `operator_kod` VARCHAR(3), `musteri_id` VARCHAR(255), `hat_no` VARCHAR(50), `hat_durum` CHAR(1), `hat_durum_kodu` VARCHAR(10), `hat_durum_kodu_aciklama` VARCHAR(255), `hizmet_tipi` VARCHAR(50), `musteri_tipi` VARCHAR(20), `abone_baslangic` VARCHAR(14), `abone_bitis` VARCHAR(14), `abone_adi` VARCHAR(100), `abone_soyadi` VARCHAR(100), `abone_tc_kimlik_no` VARCHAR(11), `abone_pasaport_no` VARCHAR(50), `abone_unvan` VARCHAR(250), `abone_vergi_numarasi` VARCHAR(20), `abone_mersis_numarasi` VARCHAR(50), `abone_cinsiyet` CHAR(1), `abone_uyruk` VARCHAR(3), `abone_baba_adi` VARCHAR(100), `abone_ana_adi` VARCHAR(100), `abone_anne_kizlik_soyadi` VARCHAR(100), `abone_dogum_yeri` VARCHAR(100), `abone_dogum_tarihi` VARCHAR(8), `abone_meslek` VARCHAR(50), `abone_tarife` VARCHAR(100), `abone_kimlik_tipi` VARCHAR(10), `abone_kimlik_seri_no` VARCHAR(20), `abone_kimlik_verildigi_yer` VARCHAR(100), `abone_kimlik_verildigi_tarih` VARCHAR(8), `abone_kimlik_aidiyeti` CHAR(1), `yerlesim_il_id` INT, `yerlesim_ilce_id` INT, `yerlesim_mahalle_id` INT, `yerlesim_cadde` VARCHAR(255), `yerlesim_dis_kapi_no` VARCHAR(50), `yerlesim_ic_kapi_no` VARCHAR(50), `tesis_il_id` INT, `tesis_ilce_id` INT, `tesis_mahalle_id` INT, `tesis_cadde` VARCHAR(255), `tesis_dis_kapi_no` VARCHAR(50), `tesis_ic_kapi_no` VARCHAR(50), `fatura_adresi_secimi` ENUM('YERLESIM', 'TESIS', 'FARKLI') DEFAULT 'YERLESIM', `fatura_il_id` INT, `fatura_ilce_id` INT, `fatura_mahalle_id` INT, `fatura_cadde` VARCHAR(255), `fatura_dis_kapi_no` VARCHAR(50), `fatura_ic_kapi_no` VARCHAR(50), `irtibat_tel_no_1` VARCHAR(20), `irtibat_tel_no_2` VARCHAR(20), `abone_adres_e_mail` VARCHAR(255), `kurum_yetkili_adi` VARCHAR(100), `kurum_yetkili_soyadi` VARCHAR(100), `kurum_yetkili_tckimlik_no` VARCHAR(11), `kurum_yetkili_telefon` VARCHAR(20), `statik_ip` VARCHAR(255), `iss_hiz_profili` VARCHAR(100), `iss_kullanici_adi` VARCHAR(255), `iss_pop_noktasi_id` INT, `nvi_verified` BOOLEAN NOT NULL DEFAULT 0, `efatura_mukellefi` ENUM('EVET', 'HAYIR', 'BILINMIYOR') DEFAULT 'BILINMIYOR', `son_guncellenme_zamani` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX `idx_rehber_client_id` (`whmcs_client_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mod_btk_abone_hareket_live` ( `id` BIGINT AUTO_INCREMENT PRIMARY KEY, `rehber_id` BIGINT, `musteri_hareket_kodu` VARCHAR(10), `musteri_hareket_aciklama` VARCHAR(255), `musteri_hareket_zamani` VARCHAR(14), `gonderildi_flag` BOOLEAN NOT NULL DEFAULT 0, `kayit_zamani` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_abone_hareket_archive` ( `id` BIGINT PRIMARY KEY, `rehber_id` BIGINT, `musteri_hareket_kodu` VARCHAR(10), `musteri_hareket_aciklama` VARCHAR(255), `musteri_hareket_zamani` VARCHAR(14), `gonderildi_flag` BOOLEAN NOT NULL DEFAULT 1, `kayit_zamani` TIMESTAMP NULL, `arsivlenme_zamani` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ftp_logs` ( `id` BIGINT AUTO_INCREMENT PRIMARY KEY, `dosya_adi` VARCHAR(255), `rapor_turu` ENUM('REHBER', 'HAREKET', 'PERSONEL'), `yetki_turu_grup` VARCHAR(50), `ftp_sunucu_tipi` ENUM('ANA', 'YEDEK'), `gonderim_zamani` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `durum` ENUM('Basarili', 'Basarisiz', 'Bekliyor', 'Atlandi') NOT NULL DEFAULT 'Bekliyor', `hata_mesaji` TEXT, `cnt_numarasi` VARCHAR(2) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_logs` ( `id` BIGINT AUTO_INCREMENT PRIMARY KEY, `log_zamani` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `log_seviyesi` ENUM('INFO', 'UYARI', 'HATA', 'DEBUG', 'KRITIK') NOT NULL DEFAULT 'INFO', `islem` VARCHAR(255), `mesaj` TEXT, `kullanici_id` INT, `ip_adresi` VARCHAR(45) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_pop_monitoring_logs` ( `id` BIGINT AUTO_INCREMENT PRIMARY KEY, `pop_id` INT NOT NULL, `log_zamani` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `durum` ENUM('ONLINE', 'OFFLINE', 'HIGH_LATENCY', 'UNKNOWN'), `gecikme_ms` INT, `detay` VARCHAR(255) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_hat_durum_kodlari_referans` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `kod` VARCHAR(10) UNIQUE, `aciklama` VARCHAR(255) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_musteri_hareket_kodlari_referans` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `kod` VARCHAR(10) UNIQUE, `aciklama` VARCHAR(255) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_kimlik_tipleri_referans` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `kod` VARCHAR(10) UNIQUE, `aciklama` VARCHAR(255), `ulke_kodu_gerekli` BOOLEAN DEFAULT FALSE ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_meslek_kodlari_referans` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `kod` VARCHAR(10) UNIQUE, `aciklama` VARCHAR(255) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_esozlesme_basvurular` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `basvuru_referans_no` VARCHAR(255) UNIQUE, `tckn` VARCHAR(11), `vkn` VARCHAR(10), `ad` VARCHAR(100), `soyad` VARCHAR(100), `unvan` VARCHAR(255), `durum` ENUM('BEKLEMEDE', 'ONAYLANDI', 'REDDEDILDI', 'HATA') NOT NULL DEFAULT 'BEKLEMEDE', `whmcs_client_id` INT, `whmcs_service_id` INT, `full_request_json` TEXT, `ret_nedeni` TEXT, `basvuru_tarihi` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `son_islem_tarihi` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_efatura_kayitlari` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `whmcs_invoice_id` INT NOT NULL UNIQUE, `fatura_uuid` VARCHAR(255) UNIQUE, `fatura_no` VARCHAR(50), `fatura_tipi` ENUM('E-FATURA', 'E-ARSIV') NOT NULL, `durum` VARCHAR(50) NOT NULL, `tutar` DECIMAL(10, 2) NOT NULL, `kdv` DECIMAL(10, 2) NOT NULL, `oiv_tutar` DECIMAL(10, 2) NOT NULL, `toplam_tutar` DECIMAL(10, 2) NOT NULL, `odeme_detay_tipi` VARCHAR(50), `odeme_detay_aciklama` VARCHAR(255), `olusturma_tarihi` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `pdf_url` VARCHAR(512), INDEX `idx_efatura_tarih` (`olusturma_tarihi`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_cevher_rapor_sablonlari` ( `id` INT AUTO_INCREMENT PRIMARY KEY, `rapor_adi` VARCHAR(100) NOT NULL, `sutun_basligi` VARCHAR(255) NOT NULL, `veri_kaynagi` VARCHAR(255) NOT NULL COMMENT 'Örn: AboneManager::getToplamSayi', `sira` INT NOT NULL DEFAULT 0 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;