-- WHMCS BTK Raporları Modülü Veritabanı Kurulum Script'i
-- Bu script, modül aktive edildiğinde çalıştırılacaktır.
-- Tüm tablolar 'IF NOT EXISTS' ile oluşturulmuştur, böylece tekrar çalıştırmada hata vermez.

-- Modülün genel ayarlarını tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_ayarlar` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `ayar_adi` VARCHAR(191) NOT NULL,
    `ayar_degeri` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `ayar_adi_unique` (`ayar_adi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BTK Yetkilendirme Türlerini ve işletmecinin sahip olduğu yetkileri tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_yetki_turleri` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `yetki_kodu` VARCHAR(50) NOT NULL,
    `yetki_aciklama` VARCHAR(255) NOT NULL,
    `secili_mi` TINYINT(1) DEFAULT 0 COMMENT '0: Seçili Değil, 1: Seçili',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `yetki_kodu_unique` (`yetki_kodu`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Abone Rehber ana verilerini tutacak tablo (BTK formatına uygun)
CREATE TABLE IF NOT EXISTS `mod_btk_abone_rehber` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `whmcs_user_id` INT DEFAULT NULL COMMENT 'tblclients.id',
    `whmcs_service_id` INT DEFAULT NULL COMMENT 'tblhosting.id, her hizmet için tek kayıt olmalı',
    `OPERATOR_KOD` VARCHAR(10) DEFAULT NULL,
    `MUSTERI_ID` VARCHAR(50) DEFAULT NULL,
    `HAT_NO` VARCHAR(50) DEFAULT NULL,
    `HAT_DURUM` CHAR(1) DEFAULT NULL COMMENT 'A, I, D, K',
    `HAT_DURUM_KODU` VARCHAR(10) DEFAULT NULL COMMENT 'EK-1 Tablosundaki Kod',
    `HAT_DURUM_KODU_ACIKLAMA` VARCHAR(255) DEFAULT NULL,
    `MUSTERI_HAREKET_KODU` VARCHAR(10) DEFAULT NULL,
    `MUSTERI_HAREKET_ACIKLAMA` VARCHAR(255) DEFAULT NULL,
    `MUSTERI_HAREKET_ZAMANI` VARCHAR(14) DEFAULT NULL COMMENT 'YYYYAAGGSSDDSS formatında',
    `HIZMET_TIPI` VARCHAR(50) DEFAULT NULL,
    `MUSTERI_TIPI` VARCHAR(50) DEFAULT NULL COMMENT 'B-BIREYSEL, G-SIRKET, K-KAMU, D-DIGER',
    `ABONE_BASLANGIC` VARCHAR(14) DEFAULT NULL COMMENT 'YYYYAAGGSSDDSS formatında',
    `ABONE_BITIS` VARCHAR(14) DEFAULT NULL COMMENT 'YYYYAAGGSSDDSS, 00000000000000 olabilir',
    `ABONE_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_SOYADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_TC_KIMLIK_NO` VARCHAR(11) DEFAULT NULL,
    `ABONE_PASAPORT_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_UNVAN` VARCHAR(255) DEFAULT NULL,
    `ABONE_VERGI_NUMARASI` VARCHAR(20) DEFAULT NULL,
    `ABONE_MERSIS_NUMARASI` VARCHAR(20) DEFAULT NULL,
    `ABONE_CINSIYET` CHAR(1) DEFAULT NULL COMMENT 'E, K, D',
    `ABONE_UYRUK` CHAR(3) DEFAULT NULL COMMENT 'ISO 3166-1 Alpha-3 Ülke Kodu',
    `ABONE_BABA_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_ANA_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_ANNE_KIZLIK_SOYADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_DOGUM_YERI` VARCHAR(100) DEFAULT NULL,
    `ABONE_DOGUM_TARIHI` VARCHAR(10) DEFAULT NULL COMMENT 'YYYY-AA-GG veya YYYYAAGG',
    `ABONE_MESLEK` VARCHAR(10) DEFAULT NULL COMMENT 'EK-6 Meslek Kodu',
    `ABONE_TARIFE` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_CILT_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_KUTUK_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_SAYFA_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_MAHALLE_KOY` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_TIPI` CHAR(1) DEFAULT NULL COMMENT 'B-ESKI, Y-YENI, P-PASAPORT, D-DIGER',
    `ABONE_KIMLIK_SERI_NO` VARCHAR(20) DEFAULT NULL,
    `ABONE_KIMLIK_VERILDIGI_YER` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_VERILDIGI_TARIH` VARCHAR(10) DEFAULT NULL COMMENT 'YYYY-AA-GG veya YYYYAAGG',
    `ABONE_KIMLIK_AIDIYETI` CHAR(1) DEFAULT NULL COMMENT 'K-KENDISI, A-ANNE, B-BABA, E-ES, V-VELI/VASI, T-TUCCR/VKF, D-DIGER',
    `ABONE_ADRES_TESIS_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_TESIS_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_TESIS_MAHALLE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_TESIS_CADDE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_TESIS_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_TESIS_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_TESIS_POSTA_KODU` VARCHAR(10) DEFAULT NULL,
    `ABONE_ADRES_TESIS_ADRES_KODU` VARCHAR(20) DEFAULT NULL COMMENT 'UAVT Kodu',
    `ABONE_ADRES_IRTIBAT_TEL_NO_1` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_IRTIBAT_TEL_NO_2` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_E_MAIL` VARCHAR(191) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_MAHALLE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_CADDE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_POSTA_KODU` VARCHAR(10) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_ADRES_KODU` VARCHAR(20) DEFAULT NULL,
    `KURUM_YETKILI_ADI` VARCHAR(100) DEFAULT NULL,
    `KURUM_YETKILI_SOYADI` VARCHAR(100) DEFAULT NULL,
    `KURUM_YETKILI_TCKIMLIK_NO` VARCHAR(11) DEFAULT NULL,
    `KURUM_YETKILI_TELEFON` VARCHAR(20) DEFAULT NULL,
    `KURUM_ADRES` TEXT DEFAULT NULL,
    `AKTIVASYON_BAYI_ADI` VARCHAR(255) DEFAULT NULL,
    `AKTIVASYON_BAYI_ADRESI` TEXT DEFAULT NULL,
    `AKTIVASYON_KULLANICI` VARCHAR(100) DEFAULT NULL,
    `GUNCELLEYEN_BAYI_ADI` VARCHAR(255) DEFAULT NULL,
    `GUNCELLEYEN_BAYI_ADRESI` TEXT DEFAULT NULL,
    `GUNCELLEYEN_KULLANICI` VARCHAR(100) DEFAULT NULL,
    `STATIK_IP` VARCHAR(255) DEFAULT NULL,
    `ISS_HIZ_PROFILI` VARCHAR(100) DEFAULT NULL,
    `ISS_KULLANICI_ADI` VARCHAR(100) DEFAULT NULL,
    `ISS_POP_BILGISI` VARCHAR(255) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_rehber_whmcs_user_id` (`whmcs_user_id`),
    UNIQUE INDEX `uidx_rehber_whmcs_service_id` (`whmcs_service_id`),
    INDEX `idx_rehber_abone_tc_kimlik_no` (`ABONE_TC_KIMLIK_NO`),
    INDEX `idx_rehber_abone_vergi_numarasi` (`ABONE_VERGI_NUMARASI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Abone Hareketlerini anlık olarak yakalayıp geçici olarak saklayacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_abone_hareket_canli` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `abone_rehber_id` BIGINT DEFAULT NULL COMMENT 'mod_btk_abone_rehber.id ile FK',
    `whmcs_user_id` INT DEFAULT NULL,
    `whmcs_service_id` INT DEFAULT NULL,
    `OPERATOR_KOD` VARCHAR(10) DEFAULT NULL,
    `MUSTERI_ID` VARCHAR(50) DEFAULT NULL,
    `HAT_NO` VARCHAR(50) DEFAULT NULL,
    `HAT_DURUM` CHAR(1) DEFAULT NULL,
    `HAT_DURUM_KODU` VARCHAR(10) DEFAULT NULL,
    `HAT_DURUM_KODU_ACIKLAMA` VARCHAR(255) DEFAULT NULL,
    `MUSTERI_HAREKET_KODU` VARCHAR(10) DEFAULT NULL,
    `MUSTERI_HAREKET_ACIKLAMA` VARCHAR(255) DEFAULT NULL,
    `MUSTERI_HAREKET_ZAMANI` VARCHAR(14) DEFAULT NULL COMMENT 'YYYYAAGGSSDDSS formatında',
    `HIZMET_TIPI` VARCHAR(50) DEFAULT NULL,
    `MUSTERI_TIPI` VARCHAR(50) DEFAULT NULL,
    `ABONE_BASLANGIC` VARCHAR(14) DEFAULT NULL,
    `ABONE_BITIS` VARCHAR(14) DEFAULT NULL,
    `ABONE_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_SOYADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_TC_KIMLIK_NO` VARCHAR(11) DEFAULT NULL,
    `ABONE_PASAPORT_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_UNVAN` VARCHAR(255) DEFAULT NULL,
    `ABONE_VERGI_NUMARASI` VARCHAR(20) DEFAULT NULL,
    `ABONE_MERSIS_NUMARASI` VARCHAR(20) DEFAULT NULL,
    `ABONE_CINSIYET` CHAR(1) DEFAULT NULL,
    `ABONE_UYRUK` CHAR(3) DEFAULT NULL,
    `ABONE_BABA_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_ANA_ADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_ANNE_KIZLIK_SOYADI` VARCHAR(100) DEFAULT NULL,
    `ABONE_DOGUM_YERI` VARCHAR(100) DEFAULT NULL,
    `ABONE_DOGUM_TARIHI` VARCHAR(10) DEFAULT NULL,
    `ABONE_MESLEK` VARCHAR(10) DEFAULT NULL,
    `ABONE_TARIFE` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_CILT_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_KUTUK_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_SAYFA_NO` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_MAHALLE_KOY` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_TIPI` CHAR(1) DEFAULT NULL,
    `ABONE_KIMLIK_SERI_NO` VARCHAR(20) DEFAULT NULL,
    `ABONE_KIMLIK_VERILDIGI_YER` VARCHAR(100) DEFAULT NULL,
    `ABONE_KIMLIK_VERILDIGI_TARIH` VARCHAR(10) DEFAULT NULL,
    `ABONE_KIMLIK_AIDIYETI` CHAR(1) DEFAULT NULL,
    `ABONE_ADRES_TESIS_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_TESIS_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_TESIS_MAHALLE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_TESIS_CADDE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_TESIS_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_TESIS_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_TESIS_POSTA_KODU` VARCHAR(10) DEFAULT NULL,
    `ABONE_ADRES_TESIS_ADRES_KODU` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_IRTIBAT_TEL_NO_1` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_IRTIBAT_TEL_NO_2` VARCHAR(20) DEFAULT NULL,
    `ABONE_ADRES_E_MAIL` VARCHAR(191) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_IL` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_ILCE` VARCHAR(100) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_MAHALLE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_CADDE` VARCHAR(255) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_DIS_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_IC_KAPI_NO` VARCHAR(50) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_POSTA_KODU` VARCHAR(10) DEFAULT NULL,
    `ABONE_ADRES_YERLESIM_ADRES_KODU` VARCHAR(20) DEFAULT NULL,
    `KURUM_YETKILI_ADI` VARCHAR(100) DEFAULT NULL,
    `KURUM_YETKILI_SOYADI` VARCHAR(100) DEFAULT NULL,
    `KURUM_YETKILI_TCKIMLIK_NO` VARCHAR(11) DEFAULT NULL,
    `KURUM_YETKILI_TELEFON` VARCHAR(20) DEFAULT NULL,
    `KURUM_ADRES` TEXT DEFAULT NULL,
    `AKTIVASYON_BAYI_ADI` VARCHAR(255) DEFAULT NULL,
    `AKTIVASYON_BAYI_ADRESI` TEXT DEFAULT NULL,
    `AKTIVASYON_KULLANICI` VARCHAR(100) DEFAULT NULL,
    `GUNCELLEYEN_BAYI_ADI` VARCHAR(255) DEFAULT NULL,
    `GUNCELLEYEN_BAYI_ADRESI` TEXT DEFAULT NULL,
    `GUNCELLEYEN_KULLANICI` VARCHAR(100) DEFAULT NULL,
    `STATIK_IP` VARCHAR(255) DEFAULT NULL,
    `ISS_HIZ_PROFILI` VARCHAR(100) DEFAULT NULL,
    `ISS_KULLANICI_ADI` VARCHAR(100) DEFAULT NULL,
    `ISS_POP_BILGISI` VARCHAR(255) DEFAULT NULL,
    `gonderildi` TINYINT(1) DEFAULT 0 COMMENT '0: Gönderilmedi, 1: Gönderildi',
    `gonderildigi_dosya_adi` VARCHAR(255) DEFAULT NULL,
    `gonderme_zamani` TIMESTAMP NULL DEFAULT NULL,
    `cnt_numarasi_hareket` VARCHAR(2) DEFAULT '01' COMMENT 'Hareket dosyası tekrar gönderilirse artacak CNT',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`abone_rehber_id`) REFERENCES `mod_btk_abone_rehber`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX `idx_hareket_whmcs_service_id` (`whmcs_service_id`),
    INDEX `idx_hareket_gonderildi` (`gonderildi`),
    INDEX `idx_hareket_musteri_hareket_zamani` (`MUSTERI_HAREKET_ZAMANI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Arşivlenmiş abone hareketlerini tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_abone_hareket_arsiv` LIKE `mod_btk_abone_hareket_canli`;
ALTER TABLE `mod_btk_abone_hareket_arsiv` ADD COLUMN `arsivlenme_tarihi` TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER `created_at`;
ALTER TABLE `mod_btk_abone_hareket_arsiv` DROP INDEX `idx_hareket_gonderildi`;
ALTER TABLE `mod_btk_abone_hareket_arsiv` MODIFY COLUMN `gonderildi` TINYINT(1) DEFAULT 1;

-- Personel Departmanları Tablosu
CREATE TABLE IF NOT EXISTS `mod_btk_personel_departmanlari` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `departman_adi` VARCHAR(191) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `departman_adi_unique` (`departman_adi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Personel bilgilerini tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_personel` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `admin_id` INT NOT NULL COMMENT 'tbladmins.id ile ilişkili',
    `firma_unvani` VARCHAR(255) DEFAULT NULL,
    `tc_kimlik_no` VARCHAR(11) DEFAULT NULL,
    `uyruk_iso_kodu` CHAR(3) DEFAULT 'TUR' COMMENT 'Personelin uyruğu, ISO 3166-1 Alpha-3',
    `unvan_gorev` VARCHAR(255) DEFAULT NULL,
    `departman_id` INT DEFAULT NULL,
    `mobil_telefonu` VARCHAR(20) DEFAULT NULL,
    `sabit_telefonu` VARCHAR(20) DEFAULT NULL,
    `ev_adresi` TEXT DEFAULT NULL,
    `acil_durum_kisi_adi` VARCHAR(255) DEFAULT NULL,
    `acil_durum_kisi_telefonu` VARCHAR(20) DEFAULT NULL,
    `ise_baslama_tarihi` DATE DEFAULT NULL,
    `isten_ayrilma_tarihi` DATE DEFAULT NULL,
    `is_birakma_nedeni` TEXT DEFAULT NULL,
    `btk_listesine_eklensin` TINYINT(1) DEFAULT 1 COMMENT '0: Hayır, 1: Evet',
    `gorev_bolgesi_il_id` INT DEFAULT NULL,
    `gorev_bolgesi_ilce_id` INT DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `admin_id_unique` (`admin_id`),
    FOREIGN KEY (`departman_id`) REFERENCES `mod_btk_personel_departmanlari`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- FTP'ye gönderilen rapor dosyalarının kaydını tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_gonderilen_dosyalar` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `dosya_adi` VARCHAR(191) NOT NULL,
    `dosya_tipi` ENUM('REHBER', 'HAREKET', 'PERSONEL') NOT NULL,
    `ftp_sunucu_tipi` ENUM('ANA', 'YEDEK') NOT NULL DEFAULT 'ANA',
    `gonderme_zamani` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `cnt_numarasi` VARCHAR(2) NOT NULL DEFAULT '01',
    `dosya_icerik_hash` VARCHAR(64) DEFAULT NULL COMMENT 'Dosya içeriğinin SHA256 hash değeri',
    `kayit_sayisi` INT DEFAULT 0 COMMENT 'Dosyadaki satır/kayıt sayısı',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY `dosya_adi_unique` (`dosya_adi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Adres İl Tablosu
CREATE TABLE IF NOT EXISTS `mod_btk_adres_il` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `il_adi` VARCHAR(100) NOT NULL,
    `plaka_kodu` VARCHAR(2) DEFAULT NULL,
    `uavt_kodu` VARCHAR(20) DEFAULT NULL,
    UNIQUE KEY `il_adi_unique` (`il_adi`),
    UNIQUE KEY `plaka_kodu_unique` (`plaka_kodu`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Adres İlçe Tablosu
CREATE TABLE IF NOT EXISTS `mod_btk_adres_ilce` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `il_id` INT NOT NULL,
    `ilce_adi` VARCHAR(100) NOT NULL,
    `uavt_kodu` VARCHAR(20) DEFAULT NULL,
    FOREIGN KEY (`il_id`) REFERENCES `mod_btk_adres_il`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY `uniq_il_ilce` (`il_id`, `ilce_adi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Adres Mahalle Tablosu
CREATE TABLE IF NOT EXISTS `mod_btk_adres_mahalle` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `ilce_id` INT NOT NULL,
    `mahalle_adi` VARCHAR(191) NOT NULL,
    `uavt_kodu` VARCHAR(20) DEFAULT NULL,
    `posta_kodu` VARCHAR(10) DEFAULT NULL,
    FOREIGN KEY (`ilce_id`) REFERENCES `mod_btk_adres_ilce`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY `uniq_ilce_mahalle` (`ilce_id`, `mahalle_adi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ISS POP Noktalarını tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_iss_pop_noktalari` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `pop_adi` VARCHAR(255) NOT NULL,
    `il_id` INT DEFAULT NULL,
    `ilce_id` INT DEFAULT NULL,
    `mahalle_id` INT DEFAULT NULL,
    `adres_detay` TEXT DEFAULT NULL,
    `koordinatlar` VARCHAR(100) DEFAULT NULL COMMENT 'Enlem,Boylam',
    `yayin_yapilan_ssid` VARCHAR(191) DEFAULT NULL,
    `sunucu_bilgisi` VARCHAR(255) DEFAULT NULL COMMENT 'İlişkili WHMCS sunucusu veya IP adresi',
    `aktif_mi` TINYINT(1) DEFAULT 1,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`il_id`) REFERENCES `mod_btk_adres_il`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`ilce_id`) REFERENCES `mod_btk_adres_ilce`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (`mahalle_id`) REFERENCES `mod_btk_adres_mahalle`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE KEY `yayin_yapilan_ssid_unique` (`yayin_yapilan_ssid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Modül içi logları tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_logs` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `log_tarihi` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `log_seviyesi` ENUM('INFO', 'WARNING', 'ERROR', 'DEBUG', 'CRITICAL') DEFAULT 'INFO',
    `islem` VARCHAR(255) DEFAULT NULL COMMENT 'Yapılan işlem, örn: FTP_GONDERIM, RAPOR_OLUSTURMA',
    `mesaj` TEXT DEFAULT NULL,
    `detay` TEXT DEFAULT NULL COMMENT 'Exception mesajı veya ek detaylar',
    `whmcs_admin_id` INT DEFAULT NULL,
    `ip_adresi` VARCHAR(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- WHMCS Ürün Gruplarını BTK Yetki Türleri ile eşleştirecek tablo
CREATE TABLE IF NOT EXISTS `mod_btk_product_group_mappings` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `whmcs_product_group_id` INT NOT NULL,
    `btk_yetki_turu_id` INT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`btk_yetki_turu_id`) REFERENCES `mod_btk_yetki_turleri`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE KEY `whmcs_product_group_id_unique` (`whmcs_product_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Hizmete özel ek operasyonel bilgileri tutacak tablo
CREATE TABLE IF NOT EXISTS `mod_btk_hizmet_detaylari` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `hizmet_id` INT NOT NULL COMMENT 'tblhosting.id ile ilişkili',
    `aile_filtresi_aktif` TINYINT(1) DEFAULT 0,
    `mac_adresleri` TEXT DEFAULT NULL COMMENT 'Noktalı virgül ile ayrılmış',
    `cihaz_seri_no` TEXT DEFAULT NULL COMMENT 'Noktalı virgül ile ayrılmış olabilir',
    `wifi_sifresi` VARCHAR(255) DEFAULT NULL COMMENT 'Güvenlik nedeniyle şifrelenerek saklanmalı',
    `kurulum_notlari` TEXT DEFAULT NULL,
    `cihaz_turu` ENUM('INDOOR', 'OUTDOOR', 'DIGER') DEFAULT NULL,
    `cihaz_modeli` VARCHAR(255) DEFAULT NULL,
    `kurulum_sinyal_kalitesi` VARCHAR(100) DEFAULT NULL,
    `tesis_koordinatlari` VARCHAR(100) DEFAULT NULL COMMENT 'Enlem,Boylam (Google Maps için)',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `hizmet_id_unique` (`hizmet_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BTK Referans Tabloları
CREATE TABLE IF NOT EXISTS `mod_btk_ref_hat_durum_kodlari` ( `kod` VARCHAR(10) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_musteri_hareket_kodlari` ( `kod` VARCHAR(10) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_hizmet_tipleri` ( `kod` VARCHAR(50) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_musteri_tipleri` ( `kod` CHAR(1) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_kimlik_tipleri` ( `kod` CHAR(1) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_kimlik_aidiyeti` ( `kod` CHAR(1) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_cinsiyet` ( `kod` CHAR(1) PRIMARY KEY, `aciklama` VARCHAR(50) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_hat_durum` ( `kod` CHAR(1) PRIMARY KEY, `aciklama` VARCHAR(50) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_meslek_kodlari` ( `kod` VARCHAR(10) PRIMARY KEY, `aciklama` VARCHAR(255) NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS `mod_btk_ref_ulkeler` ( `iso_kodu` CHAR(3) PRIMARY KEY, `ulke_adi_tr` VARCHAR(100) NOT NULL, `ulke_adi_en` VARCHAR(100) DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;