<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '4.4.2';
$moduleRevision = '92df51c5c5e33fdb854eef604a8b83d07ea6cd77';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/Report_Generator_For_WHMCS';